package com.online.taxi.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Auther: lsk
 * @Date: 2022/7/26 - 07 - 26 - 21:46
 * @Description: com.online.taxi.entity
 * @version: 1.0
 */
@Data
public class TagRuleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.service_type_id
     *
     * @mbggenerated
     */
    private Integer serviceTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.tag_price
     *
     * @mbggenerated
     */
    private BigDecimal tagPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.tag_desc
     *
     * @mbggenerated
     */
    private String tagDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tag_rule_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
}
